(function() {
    $.bind('command', function(event) {
        var sender = event.getSender();
        var command = event.getCommand();

        if (command.equalsIgnoreCase('batfact')) {
            var facts = [
                'Insect eating bats are worth an estimated $23 billion to the US economy as natural pest control.',
                'The bumblebee bat is the world’s smallest mammal, weighing in at 2 grams and are around 1.1 to 1.3 inches in length!',
                'While you’ve seen bats wiggle their ears, you may have also noticed their noses wiggle as well. Doing this directs their echolocation!',
                'There is a species of bat (you’re welcome https://goo.gl/7UvLUF) called the Honduran White Bat, who like to snuggle together in groups inside of leaf tents when they sleep! valeHug ',
                'There are over 1,300 species of bats! Only 3 of which are vampire bats, who yes, actually do have a blood-based diet.',
                'Vampire bats have an enzyme called “draculin” that is an anticoagulant. This makes feeding easier! Additionally, it’s being used by researchers to possibly treat strokes and heart attacks in humans.',
                'Vampire bats have heat seeking noses that they use to find the warmest spots on their prey, where the blood would be closest to the surface.',
                'There’s a “bat god” called Camazotz in Mayan mythology. It demanded ritual blood sacrifices.',
                'A species of bat called the Heart-Nosed Bat sings to claim its territory.',
                'Fruit bats have a higher alcohol tolerance than humans - probably to help with eating fermented fruit!',
                'Although flying foxes are typically called “fruit bats”, they also love flowers!',
                'The Small Flying Fox Bat is found to use its wings as an umbrella when it’s raining AND as a fan when it’s too hot!',
                'April 17th is Bat Appreciation Day!',
                'When researchers “translated” bat talk, they found that bats argue. A lot. Usually about food or sleeping arrangements.',
                'Livingstone’s Fruit Bats are the only bat with round ears.',
                'Vampire bats share food with each other by regurgitating so their friends and family don’t starve. Gross AND wholesome!',
                'Young bats aren’t able to fly until they are about 90% grown.',
                'Bats can swim. Yes, there are videos.',
                'Bats actually are not blind! Jebaited',
                'Flying foxes are typically very clean bats and spend a lot of time grooming themselves, other than when they pee on themselves to keep cool and to attract the ladies. It’s not gross, it’s just resourceful!',
                'Fruit bats don’t eat the entire fruit, they squeeze out the juices and good stuff and spit out what is called a “spat”. If they ate the whole thing, they’d be too fat to fly LUL .',
                'Bats do not have an appendix.',
                'Bats are especially susceptible to extinction due to their long gestation periods and how they typically only have one pup at a time.',
                'Bat nipples are located in their armpits.',
                'Bats are the only mammal capable of powered, continuous flight, and fly with more accuracy than most birds.',
                '20-25% of all mammal species are bats.',
                'Relative to body size, the Spotted Bat has the largest ears out of all species of bat.',
                'The vampire bat is the only species of bat that can run.',
                'Bats are actually really loud, but to humans it seems quiet because of the octave that echolocation is used at. It can go as high as 138 dB! This is as loud as a gunshot, but completely undetectable to humans.',
                'All leaf-nosed bats emit echolocation through their noses.',
                'Some baby bats babble a lot like adolescent human children.',
                'Bats are responsible for the pollination of agave, which is the plant used to make tequila. THANKS BATS!',
                'You might not be able to own a pet bat, but you can build or buy a bat house (just like birdhouses!) that bats can roost in.',
                'Most people believe bats are related to rodents. Most people are wrong.',
                'Vampire bats tend to adopt orphaned baby bats within their colony.',
                'Moths can detect echolocation and emit clicking sounds back to the bats to “jam” the echolocation, making it difficult for the bat to prey on them.',
                'Some female bats can control pregnancy by slowing the development of the embryo.',
                'The male bats in a species called Chapin’s Free-Tailed Bat has a mohawk. It’s used for courtship to attract females, but also to look really cool.',
                'Tube-lipped Nectar Bats have tongues that are 1.5 times longer than their bodies. It has longest tongue relative to its body size of any mammal!',
                'Not every bat uses echolocation - like large fruit bats! They don’t need to use it, they rely on sight and smell to forage for food, as well as their strong memory to bring them back to previous feeding grounds.',
                'Most bats can’t take off from the ground, many need to drop 2 or 3 feet before taking flight. Vampire bats can take flight from the ground by doing a strong “push-up” and then off they go!',
                'Echolocation is so fine tuned, that bats can detect extremely small and thin objects like a single human hair.',
                'Bat species that eat frogs can tell the difference between safe frogs and poisonous frogs by listening to the male frogs call. Also some bats eat frogs.',
                'A group of bats is called a colony! Not as cool as a murder of crows...but that’s fine.',
                'Guano was used during the Civil War as gunpowder.',
                'Australian bats are not poisonous, but they don’t eat Tim Tams either valeTaxic ',
                'There is a park next to the Sydney Opera House that was home to many giant Flying Foxes that flew freely and lived together. The bats may have been evicted at this time, but when has the Australian wildlife ever listened to the Australian government?',
                'Evidence found of the earliest bat-like mammal dates back ~50 million years ago.',
                'Vampire bats often return to and remember the same exact prey that they fed on during a previous night.',
                'Small Club-Footed bats roost INSIDE of bamboo stalks in Southeast Asia.',
                'In West Africa, Small Wooly bats live in large spider webs. Spooky.',
                'White Winged Vampire Bats are known to snuggle up to hens and pretend to be one of the chicks, then they feed off the mother hen’s blood.',
                'White nose syndrome is a deadly disease that affects nearly every single species of bat. Researchers are trying hard to find a treatment for this disease, since every single species of bat is important to the environment, and us as humans! From pollination to spreading seeds, using enzymes to treat strokes, and pest control, this world can’t live without bats :( !',
                'Bats live happily on every single continent except Antarctica.',
                'Approximately 70% of all species of bat are insect eaters.',
                'In China and Japan, bats have been associated with good fortune throughout history. It’s opposite for Europe and North America where bats are associated with witchcraft and evil.',
                'Pipistrelle bats may weigh less than 2 pennies, but can actually eat up to 3,000 bugs in one day.',
                'Dracula originated in Eastern Europe, but vampire bats don’t even live there. They actually are found in Central & South America.',
                'Bats are easily divided into 2 ‘suborders’ in classification. Yinpterochiroptera and Yangochiroptera. In the past, this was Megachiroptera (large) and Microchiroptera (small).',
                'The largest documented bat species title belongs to the Giant Golden Crowned Flying Fox. Their wingspan can get up to 5.6 feet (1.7m) long.',
                'Relative to its size, bats live longer than any other mammal. Captive bats can live up to 30 or 40 years.',
                'One single Brown Bat can eat approximately 1,200 mosquitoes (or mosquito sized bugs) per hour.',
                'Less than 10 people in North America have ever contracted rabies from a bat. They will only bite in self defense and don’t care much for humans, they just wanna hang out and do their own thing mostly.',
                'The largest bat colony known in the world is located at Bracken Cave in Texas, USA. It’s holds about 15 million Mexican Free-tailed Bats.',
                'Bats have one of the highest documented rates of homosexual sexual behavior among mammals. It’s difficult to study especially with how many bat species there are and how many different mating habits they each have, but there is documentation of some bats exhibiting very...very homosexual behavior with each other. valeGasm ',
                'Tropical fruit bats are responsible for up to 95% of tree establishment in restored rainforest.',
                'Mexican Free-Tailed Bats can fly at up to 100 miles per hour.',
                'Little Brown Bats can be taken several hours by car away from their home range and find their way back. Most tropical species cannot be moved even a few miles!',
                'Bats can breathe through their wings - about 10-15% of gas exchange occurs across the wing membrane.',
                'The “fingers” in a bats wings are really the third, fourth, and fifth digit (middle, ring, and pinky fingers). The second finger has become reduced and braces the third.',
                'Sucker-footed bats have natural sticky suction cups on their wings and feet and can stick to surfaces like tree frogs, and Disc-winged bats have more “traditional” suction cups that create a vacuum to surfaces. They can each stick to completely vertical walls!',
                'Several species of bat can only be distinguished from one another by a few millimeters difference in tooth width or the length of their ear hair, but are COMPLETELY genetically distinct.',
                'Pallid bats are immune to scorpion venom, which allows them to be stung by their pray while hunting them and come out unharmed.',
                'Greater Bulldog Bats have calls that are as loud as gunshots, the loudest of any bat species, but humans are unable to hear its frequency.',
                'When using echolocation, the closer the bat is to its prey, the quicker the clicks they emit.  A “feeding buzz” is when the bat is closest to its prey.  Since it is up to 200 clickers per second, it sounds closer to a buzzing noise.',
                'After Pearl Harbor, the military attempted to use bats as tiny bombs. It didn\'t end up working, lots of money was wasted, and many bats died.',
                'Vampire bats can leap 7 feet high, which is equivalent to a human man jumping over a 7 story building.',
                'Honduran White Bats seem like they wouldn\'t be camouflaged very well since their fur is so bright, but the leaf tents they roost in reflect green hues onto their white fur. This makes them blend in with their homes extremely well!',
                'Bats have tendons in their toes which “lock” into place and is able to hold their body weight while hanging upside down. This is how they stay in place for so long! This also takes absolutely no energy for them to do, and bats will stay hanging upside down even after death because of these tendons.',
                'It\'s a myth that bats fly left out of a cave. They just fly wherever they want, actually. Usually to me, I\'m carrying.',
                'Bats are incredibly agile fliers and are able to turn directions sharply or move at extremely high speeds. The reason they are so agile is because they can move their wings asymmetrically, while birds can only move their wings symmetrically. Bats also have incredible flexibility and elasticity in their bones - more than any other mammal. This is what sets bat flight apart from bird flight.',
                'Bats belong to the order “Chiroptera” which translates to “hand wing.”',
                'Early human flight ideas/inventions (which DaVinci famously studied) were inspired by the complexity of bat flight.',
                'Bats have different “supersonic signatures” that sets them apart from each other.  This means they have different “voices” just like humans. Mothers can tell their babies apart from thousands of other bat babies because of their unique voices!',
                'Male Dyak’s Fruit Bats are one of the only known natural occurrences of *male* lactation and this may be to help feed their young along with the female bats. It hasn’t yet been observed, but it is one hypothesis of why this species of bat would have male lactation. Anyone up for researching bat lactation?',
                'Bats do in fact, have belly buttons, just like humans.',
                'Baby bats can weigh up to 1/3rd of its mother\'s body weight. Imagine a human baby being that heavy. That’s a very giant baby.',
                'Male Hammer Headed Fruit Bats honk, and they do it to attract mates. No kink shaming.',
                'Malayan Flying Foxes will fly around 40 miles in search of food!',
                'Not all bats hibernate, and some bats migrate during cold climates.',
                'Fruit bats can detect ripe fruit just by the odor. ms_boogie encourages you to sniff your fruit at the supermarket. Hone in your bat abilities, you can do it! BECOME A BAT.',
                'Some bats in found in the Panama canal can lower their heart rate from 1,000 BPM to 200 BPM to avoid starvation as food is scarce instead of just spamming "I need healing." Bats who hibernate will have an even lower BPM.',
                'Hardwicke’s Wooly Bat roost inside carnivorous pitcher plants.',
                'Some bats cool off by flying low over water and skimming the surface. They then can drink the water from their soaked belly fur!',
                'Research on how bats successfully navigate through hundreds of other bats flying together in a colony is inspiring the engineering of safer self-driving cars. Bats are the future.',
                'Egyptian fruit bat has 1,000 different vocalizations and their “dialect” is unique only to the colony they are raised in. Only bats that spend a lot of time on the internet will talk a little differently than their colony, particularly smol bats.',
                'Since blood is not very nutritious, Vampire Bats get assistance processing blood from microbes in their guts.',
                'It’s believed that some species of bats are nocturnal simple for the fact that there is no food competition with birds during the night time.',
                'Sad fact - wind turbines will explode little bats lungs due to the low air pressure valeCry',
                'Young Vampire Bats are more likely to explore novel objects than adults.',
                'Bat can learn behaviors from other species of bats.',
                'White-throated Round-eared bats roost inside termite colonies.',
                'Some bats eat fish, like the fish-eating Myotis. They emit echolocation over water sources to sense a disturbance near the surface, and then they swoop in.',
                'Nectar-eating bats use their tongues different ways to eat nectar from plants. Some use it as a spoon, others have long tongues used like a straw.',
                'Pallas’s Long-tongued bat has the fastest metabolism of any animal, as 78% of energy comes from recently consumed sugars.',
                'Bats typically try to stay out of bad weather, unless the pups are absolutely starving.',
                'Bats are able to carry pollen farther than any other animal.',
                'Mexican Free Tailed Bats helped researchers discover that many species of bats, including Mexican Free-tailed Bats themselves, will sing to attract mates.',
                'Baby flying foxes require daily sun exposure to get the vitamin D they need for rapid wing bone growth - which can be up to 1mm per day - just like Mercy mains need daily sun exposure to get the vitamin D they need to left-click (aka @Vale go outside).',
                'Bats respond to distress calls, but not normally to help. It’s typically just to assess if they are at any risk themselves.',
                'Like human fingerprints, a bat’s wing prints are unique and can be used for identification.',
                'Some bats have special greetings when they return to the roost (like a special handshake!).  The more important a bat is in the hierarchy, the more elaborate the greeting.',
                'Male Sack Wing Bats concoct a “perfume” in their wing sacks to attract mates. It’s not made out of sunshine and flowers; you don’t want to know what they make it with…',
                'Panama Canal alone has ~72 separate bat species that live there.',
                'As we know, herbivore means “plant based diet”, carnivore means “meat based diet”. Sanguivore is a “fresh blood based diet” and Frugivore is a “fruit based diet”!',
                'Vampire bats are highly sensitive to the cold since they have no fat reservoirs from their blood based diet.',
                'Some bats mark their territory in the same way your household cat will - by rubbing their faces on the territory they claim as their own!',
                'Tears in wings are not rare for bats. Luckily, wing membranes are very likely to regenerate themselves and heal up just fine!',
                'Many species of bats, like Common Tent-making Bats or Honduran White Bats, will chew leaf tents in a way that will cause it to fold into shape. Think perforated paper from a notebook!',
                'The oldest lived bat ever found was a 41 year old Brandt’s bat from Russia.',
                'Since bats live abnormally long lifespans for their size, researchers are studying if their genes are particularly resistant to damage. Super bats? Recent studies are showing in the Myotis genus, that this may be to the length of their telomeres that don’t shorten with age, like humans or other animals.',
                '530 species of flowering plants rely on bats as their major or EXCLUSIVE pollinator.',
                'Bats do not have hollow bones like birds.',
                'Some bats, like the Greater Sac-winged Bat roost in the open and rely on camouflage to be protected, unlike the cave-dwelling bats that we already know.',
                'Many plants have adapted strategies to attract pollinators and seed dispersers, like bees or squirrels and such.  Some plants have adapted specifically to bats!',
                'Bats have pollinated bananas for over 50 million years.',
                '18 million years ago, bats “stole” a gene called VP35 from an ancestor of the Ebola virus. But bats don’t spread Ebola -- the bat form of the gene works differently! Researchers think the VP35 gene may help regulate bats’ immune system.',
                'In Austin, Texas, they released Brazilian free-tailed bats into the city to combat bug colonies that were threatening the crops. It worked! The bats colonized and have been an invaluable pest control to the crops in Austin.',
                'Female Eastern Red bats are one of the few species capable of having a larger litter of pups. Because of this, they have four nipples instead of the normal two.',
                'A vampire bat’s fangs are so sharp, you wouldn’t even feel them biting you! But no worries, Vampire bats rarely feed on humans, prefer livestock, AND are only native to Central & South America.',
                'The Ussurian tube-nosed bat hibernates inside of dens made of snow. (Tiny little bat igloos!) Despite being made of snow, it successfully keeps the bat warm throughout the winter.',
                'Only six bat species worldwide are known to have naturally white fur.',
                'You may think wrinkly-faced bats look ugly (Ms Boogie finds every bat cute) but the wrinkles have purpose! They can actually help control and direct their echolocation.',
                'Honduran White Bats have left the SPF 100 at home. They have developed a special patch of pigmented tissue on top of their heads that protects them from the sun instead! It’s colored by melanin - something we also have as humans.',
                'While it’s true fruit bats don’t use echolocation, there is one exception! The Egyptian fruit bat is the only fruit eating bat known to use echolocation like its bug eating cousins. It’s used for navigation, and not hunting!',
                'Northern Ghost Bats are known to sing while they eat.',
                'In Mexico, there is a spot called “Volcán de los Murciélagos”, or “Bat Volcano” that was sacred to the Maya, and was believed to be an entrance to the underworld. It’s dubbed the “Bat Volcano” because it “erupts” with bats as dusk falls.',
                'Townsend’s Big Eared Bat is nicknamed a “whisper bat”, because they use echolocation at a lower frequency. This is because they primarily hunt moths, and moths are able to pick up on higher frequencies.',
                'October is Bat Appreciation Month! There is also a week in October that is celebrated as Bat Week!',
                'The Painted Bat looks very festive for Halloween with its bright orange and black fur. Trick or treat!',
                'The Azores Noctule and the Blyth’s Horseshoe Bat are the only bat species in the world that hunt insects principally by day. The Azores Noctule also has a really cool name.',
                'We know that bats are just as important as bees and butterflies for pollinating plants, but the Pallas’s Long-Tongued Bat’s hair is specifically designed to hold on to pollen particles so the bat can transfer the pollen from plant to plant!',
                'Researchers have found the secret to pro-level, complex bat flight - tiny, microscopic hairs on most bats wings, that feel their way through the air. When these hairs were removed, bats were found to make wider turns, or weren’t able to slow as quickly.',
                'Bats without fur?! The Naked Bulldog Bat, or the Greater Naked Bat, or even just the Hairless Bat lives up to its many names. It’s mostly hairless, save for a few patches around its neck, head, toes, and tail areas.',
                'Compared to other Flying Foxes, the Samoan Flying Fox is very little! It weighs just one pound and the adult wing span reaches up to 3 feet. This species is also known to be monogamous, as the males tend to stick to one mate at a time.',
                'The Bacardi Bat is one of the world’s most well known logos. The creators of Bacardi Rum noticed the many fruit bats hanging in the rafters of their Cuban distillery, and thought of them to be a sign of good fortune. They weren’t wrong - these fruit bats helped pollinate their sugar cane fields!',
                'While bats aren’t inherently blind, they can suffer from blindness as a disability! However, since their other senses are so fine tuned, they aren’t at a disadvantage if they have any vision problems.',
                'A bat’s brain is very similar to a human’s. Their hippocampus is much like ours, which is important for spatial and social memory. Bats help us understand how our own brains work in a social setting. These tools are what helped humans form such complex and large societies.',
                'Bats tend to have hearts that are three times larger and pump more blood than any other mammal their size!',
                'Bats can trap air in their wings to use as insulation. valeComfy',
                'Nectar eating bats can hover just like hummingbirds, but not for as long! It takes an incredible amount of energy, so they have the fastest metabolism of any mammal.',
                'Bats were first classified in the Primates order in 1758 before receiving their own order 20 years later.',
                'Blood doesn’t rush to the head of an upside-down bat because of special, one-way valves in its arteries! It prevents the blood from flowing backwards.',
                'Bats have a built-in compass that is incredibly sensitive to the Earth’s magnetic field. It helps them distinguish north and south!',
                'Megabats have the largest brains relative to their body size out of any other bats.',
                'Insect eating bats have guano that sparkles. That’s like the same as unicorns, right?',
                'Bats can hear from anywhere between 20 to 120,000 Hz. For comparison, humans can only hear from 20 to 20,000 Hz.',
                'Bat pollination has its own term! It’s called ‘chiropterophily’.',
                'Hoary Bats are so soft and fuzzy, they’re known to use their tails as blankets to keep warm!',
                'Rescued baby bats are swaddled in tiny blanket burritos to mimic being wrapped in their mother’s wings! It keeps them feeling happy, safe, and warm. It also makes them look super cute. Batrittos valeComfy',
                'The rain makes it WAY harder for a bat to use echolocation. The water can retract soundwaves, so the raindrops interfere with the bats ability to echolocate.',
                'Some species of bats are able to see ultraviolet light, something humans can’t see.',
                'Desert bats, like the California Leaf-nosed bat, can live without water for at least six weeks!',
                'Lesser Long-nosed bats follow what is called the “nectar trail”, which is a blooming of cacti and agave plants between New Mexico and Southern Arizona. It drinks the nectar of these plans, and along the way, pollinates each one!',
                'Bats have the ability to carry diseases without getting ill themselves. A new hypothesis offers that the reason bats are able to do this, is because of energy expenditure and body temperature! Since it is higher than other mammals, the high temp protects against harmful pathogens.',
                'Bats are able to temporarily disconnect their eardrums, because bat calls are loud enough to deafen each other! This is called the tympanic reflex.',
                'Which came first, the chicken or the egg? Echolocation or flight in bats? Biologists go back and forth on this, after studying 53 million year old bat fossils. Some say echolocation came first (history shows Shrews also do it), others say that flight likely developed before echolocation.',
                'It is well known that many bats roost in varying sized colonies together and take care of each other. Other species, like the Eastern Red bat like to live alone! Roosting habits are varied between species, but it is a unique phenomenon that a bat would rather roost alone.',
                'The word “bat” was first used in the 1570’s.',
                'Six species of bats don’t actually hang upside down like the rest of their Chiroptera family. These species are typically the ones that have sucker feet, or suction cups that help them grip while they roost.',
                'The Mexican Free-tailed bat will steal prey from rival bats, by jamming their echolocation sensors. It sabotages the hunt of the rival bat so the Mexican Free-tailed bat can take it for themselves!',
                'Fully grown Grey-headed Flying Foxes can reach speeds of up to 25 mph (about 40 kph) while carrying AND feeding their young at the same time.',
                'Bats are still widely unknown by researchers. Biologists still discover new species every year!',
                'Bats in the Free-tailed family are capable of long-distance flying. They use a biological radiation mechanism that allows them to regulate heat while they travel.',
                'We know most bats are nocturnal, and that is possibly because there is no competition for food with birds, who are typically diurnal. Not all bats are nocturnal however! Some are diurnal, and those bats live on islands that have less of a bird population to have to compete with.',
                'There is a superstition in Bolivia that bat blood can cure epilepsy. Bats are capable of many amazing things, but curing epilepsy is not one of them.',
                'The skin on a bat’s wing is called the “patagium”.',
                'Many bat species congregate in smaller colonies with one male and many females - called harems. Single male bats with no harems live together with other single male bats, called bachelor colonies.',
                'Echolocation can reach prey up to 10 meters (32 ft) away.',
                'Two libraries in Portugal have resident bats that act as pest control. At night, they hunt the insects that would otherwise damage all of the books!',
                'Bartok is a fictional bat in the movie Anastasia. He is portrayed as an albino bat of no particular species, and was Don Bluth’s favorite character to draw in the movie.',
                'Flying foxes are the first non-domesticated animal to understand human gestures. They will follow a pointing finger without training!',
                'Particular bones in a bats wings (phalanges and metacarpal bones) are less mineralized than other bones of their wings, allowing them to flex these parts as necessary while flying.',
                'Measuring the intelligence of a bat is difficult, but some studies in cognitive tests show that flying foxes are as smart as dogs!',
                'Vampire bats got their name from Vampires. Vampire mythologies existed a lot longer throughout several ancient cultures before vampire bats were documented and named in 1810! Bram Stoker took the inspiration from the vampire bats being named after these cryptids, which then gave us Dracula as we know him in 1897.',
                'Some tree roosting bats can use their wings as camouflage to protect themselves and stay hidden. The color and natural way a bat will wrap its wings around itself makes the bat look like a dead leaf!',
                'Relative to body size, mother bats will produce more milk for their pups than a dairy cow will for their calves!',
                'Certain female bats, like the Daubenton’s bat, will develop a black chin spot in the autumn to indicate she is ready to mate! This is a special type of “sexual dimorphism”, meaning you are able to visually indicate the difference between a male and a female of a certain species. Think peacocks (males are colorful with large feathers) and peahens (females are small and brown)!',
                'Through the taxonomic tree maze, bats are found under Kingdom Animalia, Phylum Chordata, Class Mammalia, and then Order Chiroptera, which is where every single bat species is listed.',
                'Only one to two human deaths per year in the US have been associated with rabies contracted from bats! Bats avoid human contact, so you will be safe if you simply just do not pick up a bat.',
                'About 80 different medicines are derived from plants that rely primarily on bats for their survival!',
                'An old Aesop fable told the story about a bat that borrowed money. It hid during the day, only to come out at night to avoid paying back the owed money. According to Aesop, this is why bats only come out at night.',
                'Another Aesop fable told the story of a bat who, in a battle of beasts and birds, kept switching sides to who he thought would win at any time the tide turned. After the war ended, the animals punished him for being deceitful by banning him to fly alone at night.',
                'Researchers are finding that fat bats may be able to withstand the deadly and devastating effects of White Nose Syndrome. The mortality rate of WNS was 58%, but higher fat stores while hibernating can bump this up to 70%.',
                'The Austin, TX Congress Avenue Bridge holds a hefty roost 1.5 million Mexican-free Tailed Bats. Tourists will gather on the bridge during feeding times to watch the colony fly out for a meal. This bat tourism brings the city bring in 10 MILLION dollars in tourist revenue each year!',
                'Three states have an “Official State Bat”. Texas and Oklahoma with the Mexican-free Tailed Bat, and Virginia with the Virginian Big-eared Bat. Hawaii has the Hawaiian Hoary Bat as their “Official State Land Mammal”. Yeah, I know they fly, I don’t get it either!',
                'Echolocating bat species located closer to the equator have been found to use a less refined “version” of echolocation, unlike their cousins who have a more sophisticated echolocation technique. That’s because life at the equator is too easy and meals are plentiful, so they don’t have to work as hard!',
                'Flowers that depend on bat pollination emit a musty, rotten order to attract bats.',
                'Since bats don’t land to drink water, it is important to have available unobstructed airspace around a body of water for them to be able to fly down and drink water to stay hydrated.',
                'Some bat species offer gifts to potential female mates. Vampire bats will share a meal, while White-throated Round-eared bats will offer up an entire empty termite colony as a home, as long as she’ll include him as a roommate!',
                'Bats don’t show signs of aging, so it’s difficult for researchers to determine the age of one unless they have well kept records on one specific bat. A 40 year old bat chasing down an insect is the equivalent of a 100 year old human sprinting through an obstacle course.',
                'The title of Fastest Mammal On Earth goes to the Mexican Free-tailed Bat, who can clock speeds of up to 99 mph (160 km/h) in flight! To compare, the Cheetah only goes up to 68-75 mph (109-120 km/h).',
                'In traditional Samoan rituals, there is a symbol of a flying fox called “p’ea”. In traditional Samoan tattooing the wings of the p’ea wraps around a man’s legs and body from the knees to the hips to symbolize sealing and protecting a potential warrior.',
                'Celtics believed the spirits of their ancestors would return on Samhain, October 31st, and they held bonfires to ward off ghosts. Bats darted around eating the bugs drawn in by the fire, so the Celtics believed the fast-flying shapes were the spirits.  This is why bats are associated with Halloween!',
                'The Lesser Short-tailed Bat located in New Zealand has an unusual way of finding food. It crawls along the forest floor while foraging for bugs to eat, instead of hunting in flight like most bats.',
                'The Banana Bat has the longest skull of any bat in proportion to its body. No, this isn’t the cute fruit bat munching on a banana in that gif we all love. Musonycteris harrisoni is the Banana Bat and they and looks more...unique than their flying fox cousins.',
                'A naturally mummified Spotted Bat was retrieved from a cave in Arizona. Radiocarbon-dating dated this bat as being over 10,000 years old! Six other mummified bats were found, the second oldest being 2,100 years old and some being less than 300 years old. This suggests that this particular cave has been continuously used by Spotted Bats for over 10,000 years!',
                'Vampire bats are venomous because of a component in their saliva. Now we don’t mean the kind of venomous like a snake bite that can be fatal, but venomous in the way that it in some way changes the physiology of the victim. In the case of the vampire bat, the venom is an anti-coagulant enzyme and it is completely non-fatal!',
                'The bat genus ‘Myotis’ is more widely distributed throughout the world than any other bat genus! A bat species that is under the Myotis genus can be found on every continent except Antarctica.',
                'Some species of bat may reach altitudes of about 10,000-13,000ft (3,000-4,000m)!',
                'Why do bats hang upside down? Easy, this allows bats to simple let go of their perch and drop a bit midair before taking flight! It helps with avoiding prey efficiently, as well as conserving energy.',
                'It is essential not to wake hibernating bats. Doing this will burn through their fat reservoir they have stored for the winter, and they will starve because of it. Hibernating bats must never be disturbed!',
                'Spotted Bats are very punctual! They feed at the same chosen places at the same time every night, staying for the same amount of time. These bats do not suffer from ADHD ;)!',
                'Echolocation on a watt per watt, ounce per ounce basis, is believed to be billions times more efficient than anything similar developed by humans.',
                'Slit-faced Bats form “nursery colonies”  together to rear young! They do this in crocodile burrows in Africa. Crocodile burrows. Like, the predators with really big, powerful jaws. The bats and their babies live in their burrows.',
                'Free-tailed bats have the super ability to survive in places with ammonia gas concentration, which would be lethal to a human. They allow carbon dioxide to accumulate in their lungs, then detoxify the ammonia!',
                'Male wrinkle-faced bats have an excess of skin around their neck area that they can use as a mask to cover their face, which is believed to be used for courtship. Part of the “mask” has a translucent part that they can see out of. They’re ninja bats.',
                'The Andersen’s Leaf-nosed Bat has acute enough hearing to pinpoint insects that are moving on the ground.',
                'Echolocation techniques vary between bat species. The Genus Rousettus uses simple tongue clicking instead of laryngeal sounds. Some fruit bats also navigate by clicks produced by their wings! This is the only known example of an animal echolocating without using its voice.',
                'Certain bats have been known to have long lasting bonds of friendship, even when they travel long distances. Some species also exhibit altruism, a behavior where two animals live as faithful, monogamous pairs!',
                'Earlier, less developed bats were believed to be tree-dwelling mammals that were skilled climbers, and eventually evolved to be able to glide between branches. ',
                'The largest family of bats is the Vespertilionidae, and within the vesper bats Family, “Myotis” are the largest Genus.',
                'There are some noticeable differences between Microbats and Megabats other than size. One example, is that Microbats have a claw only on their first digit, whereas Megabats have a claw on their second digit as well! Most (not all) Microbats have a tail, and most Megabats do not have a tail.',
                'Since certain bats can detect ultraviolet light, flowers reflect this ultraviolet light in patterns that will help attract nectar-feeding bats locate the plant! Bees can detect this as well, since they’re as important to pollination as bats are.',
                'Wing shape is detrimental to flight abilities in terms of speed, power, and maneuverability. Shorter and wider wings are more agile and able to make quicker changes of direction at lower speeds, better for foraging. Longer and narrow wings are better at fast, efficient flying adapted to chase fast flying insects in the open air.',
                'Bats have highly efficient digestive systems. Fruit bats can consume and digest their meal completely in thirty minutes or less!',
                'Katydids altered their call frequencies to fool bats. Bats fooled them back by evolving vocal strategies to mimic a katydids mating call to locate them. Sneaky!',
                'Toxic-bodied moths communicate with bats to warn them that they’re NOT to be eaten! Bats that have previously caught one of these moths can remember this call and will avoid those moths in the future.',
                'Large microbats like the Greater Noctule can catch small birds in flight, and around 80% of its diet may be made up of birds!',
                'Male Ethiopian Epauletted Fruit Bats have cheek pouches that they use to store food, but can also be used to amplify courtship calls.',
                'New Zealand’s *only* native land mammals are two species of bats! Long-tailed Wattled Bat, and the New Zealand Lesser Short-tailed Bat.',
                'To protect caves with roosting bats, some conservations will install a sturdy, metal gate that will allow bats to fly freely between the gaps, but still prevent humans from entering during high-risk times, like hibernating seasons or when rearing young.',
                'Certain insect-eating bats use their tail membrane to help capture insects while hunting for their evening meals.',
                'The Ecuadorian cactus developed specialized furry material around its flowers to absorb echolocation signals to aid bats in finding their flowers more easily.',
                'The Wrinkle-faced Bat is aptly named. Centurio senex is its scientific classification name, and “senex” means “old man”.',
                'The Monfort Bat Sanctuary is a conservation group in the Philippines. They say that for every square meter, there are approximately 640 bats roosting on the rock formations of the natural sink hole located on their sanctuary!',
                'There are 79 different bat species in the Philippines!',
                'It’s believed that the California Leaf-nosed Bat is able to maneuver in flight better than any other bat species! Must be the ears…(just kidding).',
                
            ];

            $.inidb.incr('commandCount', event.getCommand(), 1);
            var count = $.inidb.get('commandCount', event.getCommand());
            $.say(facts[count % facts.length]);
            return;
        }
    });

    $.bind('initReady', function() {
        $.registerChatCommand('./commands/batfact.js', 'batfact', 7);
    });
})();
